name: Push/PR pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  TAG: "v0.0.0" # not needed for go releaser, but kept for uniformity
  REPO_FULL_NAME: ${{ github.event.repository.full_name }}
  ORIGINAL_REPO_NAME: "newrelic/nri-docker"
  GO_VERSION: '1.18'
  DOCKER_LOGIN_AVAILABLE: ${{ secrets.OHAI_DOCKER_HUB_ID }}

jobs:
  test-build:
    name: Test binary compilation for all platforms:arch
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        if: ${{env.DOCKER_LOGIN_AVAILABLE}}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
      - name: Build all platforms:arch
        run: make ci/build
      - name: e2e-test
        if: ${{ steps.check.outputs.CREATE_RELEASE == 'true'}}
        uses: newrelic/newrelic-integration-e2e-action@v1
        with:
          spec_path: exporters/${{ steps.check.outputs.NAME }}/e2e/e2e_spec.yml
          account_id: ${{ secrets.ACCOUNT_ID }}
          api_key: ${{ secrets.API_KEY }}
          license_key: ${{ secrets.LICENSE_KEY }}
